knowledge_base:
  auto_build_tree: true
  auto_index: true
  documents_dir: ./knowledge/documents
  embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  tree_index_path: ./knowledge/index/tree.json
  vector_dir: ./knowledge/vectors
model:
  api_base: ''
  api_key: ''
  name: ''
  provider: ''
  temperature: 0.7
ui:
  max_history: 10
  theme: soft
  title: MTC-UI
